version: '3'
services:
  web:
    env_file:
     - .env
    build: .
    ports:
     - "3000:3000"
    depends_on:
  mongo:
    container_name: mongodb
    image: "mongo"
    ports:
     - 27017:27017
